tenant: nplusp
app: github-notifier
service: github-notifier

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: eu-west-1

functions:
  slack-notifications:
    handler: app/webhooks/notifier.Webhooks::Notifier.handler
    events:
     - http:
         path: slack_notify
         method: post
